apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeapp-deployment
spec:
  selector:
    matchLabels:
      app: employeeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: employeeapp
    spec:
      containers:
        - name: employeeapp
          image: thedevopsrookie/employeeapp:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: employeeapp-svc
spec:
  selector:
    app: employeeapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancercd